// Sample forecast data for local development when Redis has no seed data.
// Not used in production (guarded by missing UPSTASH_REDIS_REST_URL).

import type { Forecast } from '../../../../src/generated/server/worldmonitor/forecast/v1/service_server';

const NOW = Date.now();

export const MOCK_FORECASTS: Forecast[] = [
  {
    id: 'dev-conflict-mena-01',
    domain: 'conflict',
    region: 'Middle East',
    title: 'Gulf diplomatic tensions escalate over trade corridor disputes',
    scenario: 'Regional states impose reciprocal trade restrictions affecting key shipping lanes',
    feedSummary: 'Multiple diplomatic cables indicate rising friction between Gulf states over the proposed India-Middle East-Europe economic corridor routing.',
    probability: 0.55,
    confidence: 0.72,
    timeHorizon: '90d',
    signals: [
      { type: 'diplomatic', value: 'Recalled ambassadors from 2 capitals', weight: 0.7 },
      { type: 'economic', value: 'Tariff increases announced on 12 commodity classes', weight: 0.5 },
    ],
    cascades: [
      { domain: 'supply_chain', effect: 'Shipping insurance premiums rise 15-20%', probability: 0.6 },
      { domain: 'market', effect: 'Regional equity indices decline 3-5%', probability: 0.5 },
    ],
    trend: 'deteriorating',
    priorProbability: 0.42,
    simulationAdjustment: 0,
    simPathConfidence: 0,
    demotedBySimulation: false,
    createdAt: NOW - 3600_000,
    updatedAt: NOW - 1800_000,
  },
  {
    id: 'dev-market-currency-02',
    domain: 'market',
    region: 'East Asia',
    title: 'Central bank intervention likely in currency markets',
    scenario: 'USD/JPY approaches intervention threshold as carry trade unwinds accelerate',
    feedSummary: 'Japanese authorities have issued escalating verbal warnings. Historical patterns suggest intervention zone at 155-160 range.',
    probability: 0.68,
    confidence: 0.81,
    timeHorizon: '30d',
    signals: [
      { type: 'market', value: 'USD/JPY at 154.8, 2-year high', weight: 0.8 },
      { type: 'policy', value: 'BoJ minutes show hawkish dissent', weight: 0.6 },
    ],
    cascades: [
      { domain: 'market', effect: 'Volatility spike in Asian FX markets', probability: 0.7 },
    ],
    trend: 'stable',
    priorProbability: 0.62,
    simulationAdjustment: 0,
    simPathConfidence: 0,
    demotedBySimulation: false,
    createdAt: NOW - 7200_000,
    updatedAt: NOW - 3600_000,
  },
  {
    id: 'dev-supply-energy-03',
    domain: 'supply_chain',
    region: 'Europe',
    title: 'Winter energy supply vulnerability persists',
    scenario: 'European gas storage drawdown faster than seasonal norm',
    feedSummary: 'Storage levels at 62% vs 5-year average of 71%. LNG spot prices rising as Asian buyers compete for cargoes.',
    probability: 0.45,
    confidence: 0.67,
    timeHorizon: '120d',
    signals: [
      { type: 'infrastructure', value: 'Norwegian pipeline maintenance extended 3 weeks', weight: 0.5 },
      { type: 'weather', value: 'ECMWF forecasts below-normal temps for Q1', weight: 0.6 },
    ],
    cascades: [
      { domain: 'market', effect: 'European industrial output contracts 1-2%', probability: 0.4 },
      { domain: 'political', effect: 'Energy subsidy debates intensify in 4 EU states', probability: 0.5 },
    ],
    trend: 'deteriorating',
    priorProbability: 0.38,
    simulationAdjustment: 0,
    simPathConfidence: 0,
    demotedBySimulation: false,
    createdAt: NOW - 10800_000,
    updatedAt: NOW - 5400_000,
  },
  {
    id: 'dev-political-latam-04',
    domain: 'political',
    region: 'Latin America',
    title: 'Constitutional reform standoff deepens in major economy',
    scenario: 'Executive-judiciary conflict over judicial appointments reaches constitutional crisis threshold',
    feedSummary: 'Supreme court has blocked 3 executive orders this month. Opposition calls for impeachment proceedings gaining legislative support.',
    probability: 0.38,
    confidence: 0.59,
    timeHorizon: '60d',
    signals: [
      { type: 'institutional', value: '3 constitutional challenges pending', weight: 0.6 },
      { type: 'social', value: 'Protest frequency doubled in capital', weight: 0.4 },
    ],
    cascades: [
      { domain: 'market', effect: 'Sovereign bond spreads widen 80-120bps', probability: 0.5 },
    ],
    trend: 'deteriorating',
    priorProbability: 0.30,
    simulationAdjustment: 0,
    simPathConfidence: 0,
    demotedBySimulation: false,
    createdAt: NOW - 14400_000,
    updatedAt: NOW - 7200_000,
  },
  {
    id: 'dev-military-europe-05',
    domain: 'military',
    region: 'Eastern Europe',
    title: 'NATO eastern flank force posture adjustment expected',
    scenario: 'Alliance announces permanent brigade rotation in Baltic states',
    feedSummary: 'Defence ministerial discussions indicate consensus building for enhanced forward presence beyond current training mission scope.',
    probability: 0.62,
    confidence: 0.74,
    timeHorizon: '45d',
    signals: [
      { type: 'military', value: 'Increased ISR activity along eastern border', weight: 0.7 },
      { type: 'diplomatic', value: 'NATO HQ scheduling extraordinary session', weight: 0.5 },
    ],
    cascades: [
      { domain: 'conflict', effect: 'Counter-deployments from opposing alliance', probability: 0.4 },
      { domain: 'market', effect: 'Defence sector equities rally 5-8%', probability: 0.6 },
    ],
    trend: 'developing',
    priorProbability: 0.50,
    simulationAdjustment: 0,
    simPathConfidence: 0,
    demotedBySimulation: false,
    createdAt: NOW - 5400_000,
    updatedAt: NOW - 2700_000,
  },
  {
    id: 'dev-cyber-global-06',
    domain: 'cyber',
    region: 'Global',
    title: 'Critical infrastructure cyber threat level elevated',
    scenario: 'State-sponsored APT group targeting energy and water utilities across multiple regions',
    feedSummary: 'CISA and ENISA jointly issued advisory on coordinated campaign against SCADA systems. 14 confirmed intrusions in past 30 days.',
    probability: 0.72,
    confidence: 0.68,
    timeHorizon: '30d',
    signals: [
      { type: 'intelligence', value: 'TTP overlap with known APT group', weight: 0.8 },
      { type: 'technical', value: 'Zero-day exploit observed in 3 countries', weight: 0.7 },
    ],
    cascades: [
      { domain: 'infrastructure', effect: 'Utility service disruptions likely in 2-3 regions', probability: 0.5 },
      { domain: 'market', effect: 'Cybersecurity stocks outperform by 10-15%', probability: 0.6 },
    ],
    trend: 'deteriorating',
    priorProbability: 0.58,
    simulationAdjustment: 0,
    simPathConfidence: 0,
    demotedBySimulation: false,
    createdAt: NOW - 1800_000,
    updatedAt: NOW - 900_000,
  },
  {
    id: 'dev-conflict-africa-07',
    domain: 'conflict',
    region: 'Sub-Saharan Africa',
    title: 'Sahel security vacuum expands as peacekeeping mandate nears expiry',
    scenario: 'Armed groups consolidate control in border regions following peacekeeping drawdown',
    feedSummary: 'Humanitarian access shrinking in 3 countries. Displacement figures up 40% year-on-year.',
    probability: 0.78,
    confidence: 0.82,
    timeHorizon: '60d',
    signals: [
      { type: 'security', value: 'Attacks on aid convoys tripled in Q4', weight: 0.8 },
      { type: 'political', value: 'Peacekeeping mandate renewal blocked in UNSC', weight: 0.7 },
    ],
    cascades: [
      { domain: 'supply_chain', effect: 'Uranium and gold supply disruptions from artisanal mining areas', probability: 0.4 },
      { domain: 'political', effect: 'ECOWAS emergency summit convened', probability: 0.6 },
    ],
    trend: 'deteriorating',
    priorProbability: 0.65,
    simulationAdjustment: 0,
    simPathConfidence: 0,
    demotedBySimulation: false,
    createdAt: NOW - 9000_000,
    updatedAt: NOW - 4500_000,
  },
  {
    id: 'dev-infra-asia-08',
    domain: 'infrastructure',
    region: 'South Asia',
    title: 'Monsoon-driven infrastructure damage assessment underway',
    scenario: 'Unprecedented rainfall strains flood defenses and transport networks',
    feedSummary: 'Rail links severed in 2 corridors. Port operations at 60% capacity. Power grid experiencing rolling outages.',
    probability: 0.52,
    confidence: 0.71,
    timeHorizon: '14d',
    signals: [
      { type: 'weather', value: 'Rainfall 180% above seasonal average', weight: 0.8 },
      { type: 'infrastructure', value: '3 major bridges declared unsafe', weight: 0.6 },
    ],
    cascades: [
      { domain: 'supply_chain', effect: 'Textile and rice exports delayed 2-3 weeks', probability: 0.6 },
      { domain: 'market', effect: 'Insurance claims surge in regional re/insurers', probability: 0.5 },
    ],
    trend: 'developing',
    priorProbability: 0.40,
    simulationAdjustment: 0,
    simPathConfidence: 0,
    demotedBySimulation: false,
    createdAt: NOW - 3600_000,
    updatedAt: NOW - 600_000,
  },
];
