name: Deploy WorldMonitor to Ubuntu

on:
  push:
    branches:
      - main # 只有推送 main 分支才会触

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          # 防止 SSH 登录时提示确认指纹导致部署卡死
          script_stop: true
          script: |
            echo "1. 进入项目目录..."
            # 这里的路径一定要改成你在服务器上 clone 代码的绝对路径！
            cd /opt/dockers/worldmonitor/source/worldmonitor
            
            echo "2. 拉取最新代码..."
            # 第一步配置的 Deploy Key 在这里发挥作用
            git pull origin main
            
            echo "3. 重新构建并无缝启动 Docker..."
            docker compose up -d --build
            
            echo "4. 清理旧镜像，释放服务器硬盘空间..."
            docker image prune -f